import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import { h1font, textfont, h2font, buttonfont, logofont } from "@/fonts";

export const metadata: Metadata = {
  title: "Financial site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${h1font.variable} ${h2font.variable} ${buttonfont.variable} ${logofont}`}>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Navbar />
          <main className={`${textfont.className} antialiased bg-darkwhite text-graphite dark:bg-dim dark:text-ivory`}>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
